name: lint

on:
  push:
    branches:
      - master
      - refactor
  pull_request:
    branches:
      - master
      - refactor

jobs:
  sort-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install isort and black
        run: |
          python -m pip install --upgrade pip
          pip install isort black
      - name: Run isort and black
        run: |
          isort .
          black .
